dist: xenial

language: node_js

services:
    - docker

env:
    - DOCKER_COMPOSE_VERSION=1.4.2

node_js:
    - "lts/dubnium"

git:
  clone: false

before_install:
    - git clone https://github.com/dlx-lisbon/dlx-contracts.git
    - git clone https://github.com/dlx-lisbon/dlx-ui.git

install:
    - (cd dlx-contracts && yarn)
    - (cd dlx-ui && yarn)

script:
    - cd dlx-ui
    - yarn build
